### PR TITLE
Add robustScale

### PR DESCRIPTION
**Pull request by jmh530**
Addressing Issue [20](https://github.com/libmir/mir-stat/issues/20), adding robustScale function.

### CODE REVIEW

**Comment by 9il** [comment]
@jmh530 need fix for CI

**Comment by jmh530** [comment]
@9il Looks like the failing CI was due to changes to mir-algorithm's RC implementation because RCArray no longer has a copy constructor. I made a small modification to fix.

**Comment by 9il** [comment]
> @9il Looks like the failing CI was due to changes to mir-algorithm's RC implementation because RCArray no longer has a copy constructor. I made a small modification to fix.

It is weird, we are using it heavily and it works. Could you please make a reduced test case to get what is wrong with RCArray?

**Comment by jmh530** [comment]
@9il It looks to be related to using `map` and `Summator` together. Below generates the same error. It also gets the same error when I removed the `move`. 

```
unittest
{
    import core.lifetime: move;
    import mir.math.common: approxEqual;
    import mir.math.sum: Summator, Summation;
    import mir.ndslice.topology: map;
    import mir.rc.array: RCArray;
    static immutable a = [2.0, 1.0];
    auto x = RCArray!double(2);
    foreach(i, ref e; x)
        e = a[i];

    Summator!(double, Summation.naive) summator;
    summator.put(x.move.map!(a => a * a));
    assert(summator.sum == 5.0);
}
```

**Pull request merged**
