### PR TITLE
Add some more continuous distributions

### PR DESCRIPTION
**Pull request by jmh530**
Adds Cauchy, Weibull, Logistic, Laplace, and Rayleigh distributions

### CODE REVIEW

**Comment by 9il** [comment]
@jmh530 That you for another excellent MR!

Unfortunately, I can't review non-breaking changes this year. It's on you, feel free to merge and tag a new release.

**Comment by jmh530** [comment]
@9il Thank you and thanks for the update. Saying "this year" makes it sound like a temporary situation rather than a permanent one. Am I correct in assuming this is a temporary situation? Will this impact work more generally on libmir? (sorry for being nosy, but a little curious, feel free to respond by email if you prefer)

**Comment by 9il** [comment]
Very likely it will be permanent. Very likely Mir will continue to receive the compiler updates and bug fixes.

**Comment by jmh530** [comment]
@9il Appreciate the update.

**Pull request merged**
