### PR TITLE
Copy latest mir-algorithm travis.yml

### PR DESCRIPTION
**Pull request by jmh530**
CI is not running in [PR #24](https://github.com/libmir/mir-stat/pull/24). Attempting to copy latest `.travis.yml` from `mir-algorithm`.

### CODE REVIEW

**Comment by jmh530** [comment]
@9il Not 100% sure this is needed. Looks like the repository needs to be enabled [here](https://travis-ci.org/github/libmir/mir-stat). I do not have permissions for it.

**Comment by 9il** [comment]
github actions seems to be better. Except maybe ARM test, should we test mir-stat for arm?

**Comment by 9il** [comment]
activated

**Comment by 9il** [comment]
there is no `test_travis` script, lets go with GH actions instead?

**Comment by jmh530** [comment]
@9il I added the other travis files. Not sure how well Github Actions will handle the complication of adding ARM (today was my first day really looking at it).

**Comment by jmh530** [comment]
@9il I'm not sure how needed it is to test for ARM. Happy to close this if you don't think it's necessary.

**Comment by 9il** [comment]
yeap, let's close it. mir-stat is quite high level to consider different backends

**Pull request closed without merging**
